version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  consumerservice:
    image: consumer-service
    container_name: consumer-service-app
    build:
      context: ./consumer
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  producerservice:
    image: producer-service
    container_name: producer-service-app
    build:
      context: ./producer
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
